version: 1.0.{build}

# Настройка среды
environment:
  nodejs_version: "20"

# Установка зависимостей
install:
  - ps: Install-Product node $env:nodejs_version
  - cd frontend # Переходим в папку frontend
  - npm install

# Сборка проекта
build_script:
  # - cd frontend
  - npm run build

# Публикация на GitHub Pages
# deploy:
#   provider: GitHub
#   auth_token:
#     secure: YOUR_ENCRYPTED_GITHUB_TOKEN # токен
#   artifact: dist # Папка с результатами сборки
#   on:
#     branch: main # Ветка, из которой происходит деплой
deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - cd frontend && npx gh-pages -d dist
  # - npx gh-pages -d dist -u "appveyor-bot <ci@appveyor>"

# only_commits:
#   paths:
#     - frontend/**