version: 1.0.{build}
image: Visual Studio 2019
stack: node 20

# Настройка среды
environment:
  nodejs_version: "20.17.0"

# Установка зависимостей
install:
  - ps: Install-Product node $env:nodejs_version
  - cd frontend # Переходим в папку frontend
  - npm install
  - npm install gh-pages --save-dev # Локальная установка gh-pages

# Сборка проекта
build_script:
  - npm run build

# Публикация на GitHub Pages
deploy_script:
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  # - cd frontend && npx gh-pages -d dist
  # - npx gh-pages -d dist -u "appveyor-bot <ci@appveyor>"
  # Деплой через gh-pages
  # - npx gh-pages -d dist -u "AppVeyor Bot <ci@appveyor.com>"
  # Явно указываем путь к папке dist внутри frontend
  # - npx gh-pages -d frontend/dist -u "appveyor-bot <ci@appveyor>"
  - if exist frontend\dist (
      cd frontend && npx gh-pages -d dist -u "appveyor-bot <ci@appveyor>"
    ) else (
      echo "Error: 'dist' folder not found"
    )